### ISSUE TITLE
Make search as a part of all students page.

### ISSUE THREAD

**Issue by mikolaz27** [AlexFoxalt/HWsPart2#4]
Add the possibility to search students on the page where we have a list of all students. 

Check ajax technology. Try to create a search based on ajax, without page reloading and change users list "on a fly" while user is typing. 

Check this: 
https://pythonru.com/primery/django-ajax
https://openfolder.sh/django-tutorial-as-you-type-search-with-ajax

**Comment by AlexFoxalt** [comment]
Wow, ok, i'll try to do smth with this stuff

**Comment by mikolaz27** [comment]
Is this part is done?
